apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-chat
  labels:
    app: jb-chat
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jb-chat
      component: app
  template:
    metadata:
      labels:
        app: jb-chat
        component: app
    spec:
      containers:
        - name: app
          image: jb-chat-prod:0.1
          env:
            - name: PORT
              value: "8888"
            - name: DIAG_PORT
              value: "8889"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
            - name: http-diag
              containerPort: 8889
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jb-chat
  name: jb-chat-svc
spec:
#  type: ClusterIP
  type: NodePort
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30888
  - name: http-diag
    port: 8889
    protocol: TCP
    targetPort: 8889
    nodePort: 30889
  selector:
    app: jb-chat

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jb-chat-ingress
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: jb-chat.cluster.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jb-chat-svc
                port:
                  number: 8888