---
common:
  k8s_namespace: jb-chat

  app_name: jb-chat
  app_port: 8888  #  App http & api port
  diag_port: 8889  # App diag port: metrics, probes, debug
  app_node_port: 30888
  diag_node_port: 30889

  replicas_count: 1
  image_path: GiDiS/jb-chat
  image_version: "{{ env='IMAGE_VERSION' }}"    # Takes IMAGE_VERSION from environment

  env:
    SEED: 0

  ingress:
    host: jb-chat.cluster.info

staging:
  k8s_namespace: jb-chat-staging
  image_path: jb-chat-staging

  env:
    SEED: 1

  ingress:
    host: jb-chat-staging.cluster.info

  templates:
    - template: configmap.yaml.j2
    - template: deployment.yaml.j2
    - template: service.yaml.j2
    - template: ingress.yaml.j2

production:
  image_path: jb-chat-prod
  replicas_count: 1 # Increase after release distributed mode

  app_node_port: 30898
  diag_node_port: 30899

  templates:
    - template: configmap.yaml.j2
    - template: deployment.yaml.j2
    - template: service.yaml.j2
    - template: ingress.yaml.j2