---
common:
  k8s_namespace: jb-chat

  app_name: jb-chat
  app_port: 8888  #  App http & api port
  diag_port: 8889  # App diag port: metrics, probes, debug
  app_node_port: 30888
  diag_node_port: 30889

  replicas_count: 1
  image_path: GiDiS/jb-chat
  image_version: "{{ env='IMAGE_VERSION' }}"    # Takes IMAGE_VERSION from environment

  env:
    SEED: 0

  ingress:
    host: jb-chat.cluster.info

  templates:
    - template: postgres-configmap.yaml.j2
    - template: postgres-storage.yaml.j2
    - template: postgres-deployment.yaml.j2
    - template: postgres-service.yaml.j2
    - template: app-configmap.yaml.j2
    - template: app-deployment.yaml.j2
    - template: app-service.yaml.j2
    - template: app-ingress.yaml.j2

  postgres:
    enabled: true
    selfhosted: true
    image: postgres:12
    host: postgres
    port: 5432
    db: postgresdb
    user: postgresadmin
    password: postgrespasswd

staging:
  k8s_namespace: jb-chat-staging
  image_path: jb-chat-staging

  env:
    SEED: 1

  ingress:
    host: jb-chat-staging.cluster.info

production:
  image_path: jb-chat-prod
  replicas_count: 1 # Increase after release distributed mode

  app_node_port: 30898
  diag_node_port: 30899
